In [1]:
import mlflow
from mlflow.models import infer_signature

In [2]:
mlflow.set_tracking_uri("http://127.0.0.1:5000")

In [3]:
mlflow.set_experiment("XXX")
with mlflow.start_run():
    mlflow.log_metric("snjy", 1000)
    mlflow.log_metric("aksh", 50)

🏃 View run mercurial-stag-244 at: http://127.0.0.1:5000/#/experiments/312577456340133905/runs/ad1a94ae98194361834dd1e978b6d0f3
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/312577456340133905


In [4]:
with mlflow.start_run():
    mlflow.log_metric("sanjay1", 1000)
    mlflow.log_metric("xperson", 50)

🏃 View run charming-conch-487 at: http://127.0.0.1:5000/#/experiments/312577456340133905/runs/6448fce3c04049c19cd99e0fe67228d9
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/312577456340133905


In [5]:
import sklearn
import numpy as np
import pandas as pd
import sklearn.datasets 
from sklearn.model_selection import train_test_split


In [6]:
X, y = sklearn.datasets.load_iris(return_X_y=True)
X_train, X_test, y_train, y_test  = train_test_split(X, y , test_size=0.2, random_state=0, stratify=y)

In [7]:
param = {
    "penalty":'l2', 
    "C":1.0, 
    "max_iter":100,
    "verbose":0
}

from sklearn.linear_model import LogisticRegression
lr =LogisticRegression(**param)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [8]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

In [9]:
print(lr.score(X_test, y_test))
print(accuracy)
print(cm)
print(cr)

1.0
1.0
[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [10]:
mlflow.set_experiment("iris-model")

with mlflow.start_run():
    mlflow.log_metric("accuracy",  accuracy)
    mlflow.log_params(param)
    mlflow.set_tag("Training information", "basic ML using iris dataset")
    signature = infer_signature(X_train, lr.predict(X_train))

    modelinfo = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="LogisticRegression",
    )

Registered model 'LogisticRegression' already exists. Creating a new version of this model...
2025/04/22 20:04:50 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LogisticRegression, version 6


🏃 View run carefree-hare-100 at: http://127.0.0.1:5000/#/experiments/247541697422847347/runs/31a9168e6bf649aab8ac6f3ce4fa8beb
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/247541697422847347


Created version '6' of model 'LogisticRegression'.


In [11]:
param = {
    "penalty":'l2', 
    "C":1.0, 
    "max_iter":500,
    "verbose":0
}

from sklearn.linear_model import LogisticRegression
lr =LogisticRegression(**param)
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [12]:

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
cr = classification_report(y_test, y_pred)

In [13]:

with mlflow.start_run():
    mlflow.log_metric("accuracy",  accuracy)
    mlflow.log_params(param)
    mlflow.set_tag("Training information", "basic ML using iris dataset")
    signature = infer_signature(X_train, lr.predict(X_train))

    modelinfo = mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=X_train,
        registered_model_name="LogisticRegression",
    )

Registered model 'LogisticRegression' already exists. Creating a new version of this model...
2025/04/22 20:04:54 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: LogisticRegression, version 7


🏃 View run popular-snipe-921 at: http://127.0.0.1:5000/#/experiments/247541697422847347/runs/595f38adef654dbea235127087716a7f
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/247541697422847347


Created version '7' of model 'LogisticRegression'.


In [14]:
modelinfo.model_uri

'runs:/595f38adef654dbea235127087716a7f/iris_model'

## inferencing and validating model  

In [15]:
from mlflow.models import validate_serving_input
import json

model_uri = modelinfo.model_uri
serving_input = """{
    "inputs" : [[5.5, 3.5, 1.3, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [5.1, 3.8, 1.9, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [5.1, 3.4, 1.5, 0.2],
       [5.5, 2.6, 4.4, 1.2],
       [6.5, 3.0 , 5.2, 2.0],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5.5, 2.4, 3.7, 1.0 ],
       [6.3, 3.4, 5.6, 2.4],
       [5.6, 3.0 , 4.1, 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [6.9, 3.1, 5.4, 2.1],
       [5.8, 2.7, 4.1, 1.0],
       [5.8, 2.7, 5.1, 1.9],
       [5.7, 2.5, 5.0 , 2.0],
       [6.7, 3.1, 4.4, 1.4],
       [7.0 , 3.2, 4.7, 1.4],
       [5.1, 3.8, 1.6, 0.2],
       [5.1, 3.8, 1.5, 0.3],
       [5.6, 2.8, 4.9, 2.0 ],
       [6.3, 2.9, 5.6, 1.8],
       [7.2, 3.0 , 5.8, 1.6],
       [5.1, 3.7, 1.5, 0.4],
       [6.7, 3.1, 4.7, 1.5],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6.0 , 2.5],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]]
}"""

import json
# parsed_input = json.loads(serving_input)

validate_serving_input(model_uri,serving_input ) # -----> only accepts json format serving-input

array([0, 1, 0, 2, 0, 1, 2, 0, 0, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 0, 0, 2,
       2, 2, 0, 1, 1, 2, 0, 0])

## Load the model back for prediction as a generic python function model

In [16]:
import mlflow.models
import mlflow.models


loaded_model = mlflow.pyfunc.load_model(modelinfo.model_uri)
predictions = loaded_model.predict(X_test)

feature = sklearn.datasets.load_iris().feature_names
data = pd.DataFrame(X_test, columns=feature)
data["prediction"] = predictions
data["actual prediction"] = y_test



In [17]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.5               3.5                1.3               0.2   
1                5.7               2.8                4.5               1.3   
2                5.1               3.8                1.9               0.4   
3                6.1               2.6                5.6               1.4   
4                5.1               3.4                1.5               0.2   

   prediction  actual prediction  
0           0                  0  
1           1                  1  
2           0                  0  
3           2                  2  
4           0                  0

### Model Registry

The MLflow Model Registry component is a centralized model store, set of APIs, and UI, to collaboratively manage the full lifecycle of an MLflow Model. It provides model lineage (which MLflow experiment and run produced the model), model versioning, model aliasing, model tagging, and annotations.

In [18]:
mlflow.set_experiment("iris-model")
with mlflow.start_run():
    mlflow.log_metric("accuracy",  accuracy)
    mlflow.log_params(param)
    mlflow.set_tag("training info", "training for v2")
    
    signature=infer_signature(X_train,lr.predict(X_train))

    ## log the model
    ## log the model
    model_info=mlflow.sklearn.log_model(
        sk_model=lr,
        artifact_path="iris_model",
        signature=signature,
        input_example=X_train,
    )


🏃 View run adorable-hog-947 at: http://127.0.0.1:5000/#/experiments/247541697422847347/runs/6ae123f6157140009db620bc0ca2944a
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/247541697422847347


In [19]:
## Inferencing from model from model registry

import mlflow.sklearn
model_name=""
model_version="latest"

model_uri=f"models:/{model_name}/{model_version}"

model=mlflow.sklearn.load_model(model_uri)
model

MlflowException: Not a proper models:/ URI: models://latest. Models URIs must be of the form 'models:/model_name/suffix' or 'models:/model_name@alias' where suffix is a model version, stage, or the string 'latest' and where alias is a registered model alias. Only one of suffix or alias can be defined at a time.